# Generated by Django 4.1.9 on 2023-05-17 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_user_chosen_name'),
        (
            'challenges',
            '0002_alter_challenge_owner_alter_challengeentry_owner_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='photosubject',
            name='voters',
            field=models.ManyToManyField(
                through='users.UserVote', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
