# Generated by Django 4.1.9 on 2023-05-23 21:15

import apps.challenges.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('challenges', '0003_photosubject_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeentry',
            name='photo',
            field=apps.challenges.models.ChallengeEntryCloudinaryField(max_length=255),
        ),
    ]
