version: '3.8'

volumes:
  db_data: {}
  db_data_backups: {}

services:
  app:
    user: '1000'
    build:
      context: ./backend
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'

  web:
    build:
      context: .
      dockerfile: ./frontend/compose/Dockerfile
      target: develop-stage
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - '9000:9000'

  db:
    image: 'postgres:14-bullseye'
    volumes:
      - db_data:/var/lib/dbql/data
    env_file:
      - ./backend/.env
