version: '3'

volumes:
  production_django_media: {}
  production_traefik: {}

services:
  app:
    build:
      context: ./backend
      dockerfile: ./compose/production/django/Dockerfile
    volumes:
      - production_django_media:/app/photo_voter/media
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  web:
    build:
      context: ./frontend
      dockerfile: ./compose/Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env

  traefik:
    build:
      context: ./backend
      dockerfile: ./compose/production/traefik/Dockerfile
    image: photo_voter_production_traefik
    depends_on:
      - app
      - web
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  redis:
    image: redis:6

  nginx:
    build:
      context: ./backend
      dockerfile: ./compose/production/nginx/Dockerfile
    image: photo_voter_local_nginx
    depends_on:
      - app
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
