# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test"
python_files = [
    "tests.py",
    "test_*.py",
]

# ==== Coverage ====
[tool.coverage.run]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/staticfiles/*",
    "*/requirements/*",
    "*/config/*",
    "*/manage.py",
]
plugins = ["django_coverage_plugin"]


# ==== black ====
[tool.black]
line-length = 88
target-version = ['py311']
skip-string-normalization = true


# ==== isort ====
[tool.isort]
line_length = 88
indent = 4
multi_line_output = 3
lines_between_types = 1
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 2
known_django = "django"
default_section = "THIRDPARTY"
known_first_party = [
    "apps",
    "config",
]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip = ["venv/"]
skip_glob = ["**/migrations/*.py"]


# ==== mypy ====
[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
no_warn_no_return = true
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "config.settings.test"

[tool.ruff]
exclude = ["migrations"]
