# Generated by Django 4.1.9 on 2023-05-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_uservote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosen_name',
            field=models.CharField(
                default='', help_text='Name that the user provided', max_length=256
            ),
            preserve_default=False,
        ),
    ]
